name: Node.js CI with Container

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: node:16-alpine
      options: --user root
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: |
        echo "Running dummy tests..."
        node -v
        npm -v
        echo "Tests completed!"